<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="karthik-PC" ignored="0" name="Test(failed)(failed)(failed)" tests="1" failures="1" timestamp="22 Apr 2020 14:57:20 GMT" time="0.003" errors="0">
  <testcase name="instagram" time="0.002" classname="frameworkdemo.testcases3">
    <failure type="java.lang.AssertionError" message="expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [10]
	at frameworkdemo.testcases3.instagram(testcases3.java:17)
	at frameworkdemo.testunner.runners(testunner.java:24)
... Removed 53 stack frames]]>
    </failure>
  </testcase> <!-- instagram -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
